#!/bin/bash -e
if [ $# != 1 ]; then
	echo "Usage: $0 <containername>"
	exit 1
fi
if [ `whoami` != "root" ]; then
    echo "This script must be run as root"
    exit 1
fi
echo "Stopping container $1..."
lxc-stop -n $1
echo "Destroying container $1..."
lxc-destroy -n $1
echo "Removing IP address of container $1 from /var/lib/lxc/ips..."
# sed with <,$1>$ to match $1 exactly with a line break at sed regex $
# (so we don't delete other shit) into into new file, move new file into old
sed "/,\<$1\>$/d" /var/lib/lxc/ips > /var/lib/lxc/new_ips
mv /var/lib/lxc/new_ips /var/lib/lxc/ips
echo "Successfully removed container $1"
